from typing import Optional
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from src.application.common.interfaces import UserRepository
from src.domain.user.entity import User
from src.infrastructure.database.models.user import UserModel

class SqlAlchemyUserRepository(UserRepository):
    """
    Implementation of the UserRepository using SQLAlchemy.
    """
    def __init__(self, session: AsyncSession):
        self.session = session

    def _to_entity(self, model: UserModel) -> User:
        """Helper to convert DB Model to Domain Entity"""
        return User(
            id=model.id,
            email=model.email,
            password_hash=model.password_hash,
            created_at=model.created_at,
            updated_at=model.updated_at
        )

    def _to_model(self, entity: User) -> UserModel:
        """Helper to convert Domain Entity to DB Model"""
        return UserModel(
            id=entity.id,
            email=entity.email,
            password_hash=entity.password_hash,
            created_at=entity.created_at,
            updated_at=entity.updated_at
        )

    async def get_by_id(self, user_id: UUID) -> Optional[User]:
        stmt = select(UserModel).where(UserModel.id == user_id)
        result = await self.session.execute(stmt)
        model = result.scalar_one_or_none()
        if model:
            return self._to_entity(model)
        return None

    async def get_by_email(self, email: str) -> Optional[User]:
        stmt = select(UserModel).where(UserModel.email == email)
        result = await self.session.execute(stmt)
        model = result.scalar_one_or_none()
        if model:
            return self._to_entity(model)
        return None

    async def save(self, user: User) -> User:
        model = self._to_model(user)
        # We use merge to handle both insert and update scenarios,
        # though for registration it's mostly insert.
        # For strict insert we could use self.session.add(model)
        self.session.add(model)
        await self.session.flush() # Ensure ID and timestamps are populated/persisted within transaction
        
        # If we were updating, we might want to refresh. For new insert, flush is enough to get IDs if generated by DB.
        # However, our UUID is generated in Domain currently. 
        # But timestamps are server_default.
        await self.session.refresh(model)
        return self._to_entity(model)
